name: Liberar reservas vencidas

on:
  schedule:
    - cron: "*/5 * * * *"   # cada 5 minutos
  workflow_dispatch:        # permite ejecutarlo manualmente

jobs:
  liberar:
    runs-on: ubuntu-latest

    steps:
      - name: Llamar endpoint liberar-reservas-vencidas
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            https://catalogo-venta.onrender.com/liberar-reservas-vencidas
